### PR TITLE
Allow easier application debugging

### PR DESCRIPTION
**Pull request by davefiddes**
These changes make it easier for STM32 applications like stm32-sine to be debugged using arm-none-eabi-gdb and openocd.

### CODE REVIEW

**Comment by jsphuebner** [comment]
did you get watchdog resets while debugging? I never did so didn't think it was necessary to disable it

**Comment by davefiddes** [comment]
I thought I did but I can't replicate any problems with the watchdog enabled today. I'd been carrying the change for 2 years. There must have been something else wrong with my debug setup or a HW problem which I've long since resolved. Sorry.

The other two changes are still nominally useful I think.

**Comment by jsphuebner** [comment]
Ok. Is there a slick way to merge only the other 2 commits?

**Comment by davefiddes** [comment]
It seems that the [established](https://stackoverflow.com/questions/36168839/how-to-remove-commits-from-a-pull-request) way to do this is for me to rebase and drop the offending commit and force push. I've done that and it seems you should be able to merge as normal.

**Pull request merged**
